import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'category',
      label: 'Get started',
      collapsible: true,
      collapsed: false,
      items: [
        'get-started/intro',
        'get-started/installation',
      ],
    },
    {
      type: 'category',
      label: 'Design system',
      collapsible: true,
      collapsed: false,
      items: [
        'design/core-concepts',
      ],
    },
  ],
  react: [
    {
      type: 'autogenerated',
      dirName: 'react',
    },
  ],
  native: [
    // {
    //   type: 'autogenerated',
    //   dirName: 'native',
    // },
    {
      type: 'category',
      label: 'Work in progress',
      collapsible: true,
      collapsed: false,
      items: [
        "placeholder"
      ],
    },
  ],
  components: [
    {
      type: 'autogenerated',
      dirName: 'components', // This should match the 'out' directory from your plugin config
    },
  ],
};

export default sidebars;
